version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=opencommunication
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_app
    ports:
      - "8000:8000"
    depends_on:
      - db
