# Generated by Django 3.1.3 on 2021-01-22 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('receivers', models.ManyToManyField(related_name='message_receivers', to=settings.AUTH_USER_MODEL)),
                ('responses', models.ManyToManyField(related_name='_message_responses_+', to='core.Message')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'sender')},
            },
        ),
    ]
