# Generated by Django 3.1.3 on 2021-01-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
    ]
